### ISSUE TITLE
Put this in the FLIF main git

### ISSUE THREAD

**Issue by jonsneyers** [goblin/arw_compressor#1]
Hi!
I think this is really nice work! This peculiar Sony format indeed needed a special approach, and it looks like you just nailed it!

Feel free to contribute this to the main FLIF git, so it will be included in the upcoming FLIF release. 
https://github.com/FLIF-hub/FLIF/tree/master/raw-tools

**Comment by goblin** [comment]
Cool, thanks, I'll make a PR to FLIF in the coming days :-)

**Comment by goblin** [comment]
https://github.com/FLIF-hub/FLIF/pull/248 is open, let's make it the one for further discussion
