### ISSUE TITLE
compilation instruction is wrong

### ISSUE THREAD

**Issue by misev** [goblin/arw_compressor#2]
It should be as follows (-lm comes last), otherwise you get link errors:
gcc -o dcraw_hack dcraw.c -lm

**Comment by goblin** [comment]
Hi,

Thanks for pointing it out :-)

Actually both commands work for me. What version of gcc are you using and what's the link error you're getting?

**Comment by misev** [comment]
Hey, I have gcc 5.4.0.
I'm getting several math function link errors, e.g.
```
$ gcc -o dcraw_hack -lm dcraw.c
dcraw.c: In function ‘sony_arw2_load_raw’:
dcraw.c:2781:21: warning: format ‘%x’ expects argument of type ‘unsigned int’, but argument 3 has type ‘long int’ [-Wformat=]
     fprintf(stderr, "ALARM: %08x%02x\n", chunk_cnt, (imin << 4) | imax);
                     ^
dcraw.c: In function ‘dcraw_main’:
dcraw.c:9874:18: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 3 has type ‘off_t {aka long int}’ [-Wformat=]
  fprintf(stderr, "IDENT: data_at=%u, size=%ux%u, half=%ux%u\n", data_offset, raw_width, raw_height, raw_width >> 1, raw_height >> 1);
                  ^
/tmp/ccd7VHO7.o: In function `ljpeg_idct':
dcraw.c:(.text+0x44c2): undefined reference to `cos'
/tmp/ccd7VHO7.o: In function `foveon_make_curve':
dcraw.c:(.text+0x122e9): undefined reference to `cos'
dcraw.c:(.text+0x12345): undefined reference to `tanh'
/tmp/ccd7VHO7.o: In function `foveon_interpolate':
dcraw.c:(.text+0x144d8): undefined reference to `floor'
dcraw.c:(.text+0x14723): undefined reference to `floor'
dcraw.c:(.text+0x1481a): undefined reference to `floor'
/tmp/ccd7VHO7.o: In function `gamma_curve':
dcraw.c:(.text+0x17dc6): undefined reference to `pow'
dcraw.c:(.text+0x17e49): undefined reference to `exp'
dcraw.c:(.text+0x17f67): undefined reference to `pow'
dcraw.c:(.text+0x18048): undefined reference to `log'
...
```

**Comment by misev** [comment]
This is really cool work btw, I can't believe it compresses so well! Unfortunately it's way too slow (mostly calls to flif), takes about 1.5 minutes per 24MB raw file.

**Comment by goblin** [comment]
Should be fixed, also the format warnings. My GCC is 6.2.1, not sure why the order matters in 5 :-)

> This is really cool work btw, I can't believe it compresses so well! Unfortunately it's way too slow (mostly calls to flif), takes about 1.5 minutes per 24MB raw file.

Thanks :-) Yeah this tool is being a little paranoid, it actually calls FLIF twice to verify the result. Also FLIF by itself is still quite slow. I use it mostly for archiving ARWs, and I run it with `xargs -P8 -n1` to take advantage of multi-core processing, but a large photo session still takes a couple of hours to compress.
